services:
  postgres:
    container_name: handball_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: handy_news
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - handy-news
    restart: unless-stopped



networks:
  handy-news:
    driver: bridge

volumes:
  postgres:
    driver: local