services:
  postgres:
    container_name: handball_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: handy_news
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - handy-news
    restart: unless-stopped

  backend:
    container_name: handy_news_backend
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/handy_news
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - handy-news

  frontend:
    container_name: handy_news_frontend
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - handy-news

networks:
  handy-news:
    driver: bridge

volumes:
  postgres:
    driver: local
