spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/handy_news
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql

